# 'Code is generated by Codex'
# frozen_string_literal: true

require 'rails_helper'

describe RuboCop::Cop::MoneyTracker::DecoratorsTelegramStructure, :config do
  include CopHelper

  subject(:offenses) { inspect_source(source, file_path) }

  let(:source) { 'class Example; end' }
  let(:file_path) { 'app/models/example.rb' }

  around do |example|
    Dir.mktmpdir do |tmp_dir|
      Dir.chdir(tmp_dir) do
        example.run
      end
    end
  end

  context 'when telegram directory exists inside decorators' do
    before do
      FileUtils.mkdir_p('app/decorators/telegram')
    end

    it 'does not register offenses' do
      expect(offenses).to be_empty
    end
  end

  context 'when telegram directory is missing inside decorators' do
    before do
      FileUtils.mkdir_p('app/decorators')
    end

    it 'registers an offense' do
      expect(offenses.size).to eq(1)
    end
  end
end
