# 'Code is generated by Codex'
# frozen_string_literal: true

require 'rails_helper'

describe RuboCop::Cop::MoneyTracker::DecoratorsFolderNaming, :config do
  include CopHelper

  subject(:offenses) { inspect_source(source, file_path) }

  let(:source) { 'class Example; end' }

  context 'when decorators subdirectories do not end with _decorators' do
    let(:file_path) { 'app/decorators/message_body_decorator.rb' }

    it 'does not register offenses' do
      expect(offenses).to be_empty
    end
  end

  context 'when file is inside decorators subdirectory ending with _decorators' do
    let(:file_path) { 'app/decorators/telegram/bot_decorators/base.rb' }

    it 'registers an offense' do
      expect(offenses.size).to eq(1)
    end
  end

  context 'when file is inside decorators subdirectory containing decorator in singular form' do
    let(:file_path) { 'app/decorators/telegram/bot_decorator/base.rb' }

    it 'registers an offense' do
      expect(offenses.size).to eq(1)
    end
  end
end
