# 'Code is generated by Codex'
# frozen_string_literal: true

require 'rails_helper'

describe RuboCop::Cop::MoneyTracker::FactoryFileName, :config do
  include CopHelper

  subject(:offenses) { inspect_source(source, file_path) }

  let(:source) { 'class Example; end' }

  context 'when file is inside app/factories and has invalid suffix' do
    let(:file_path) { 'app/factories/telegram/base.rb' }

    it 'registers an offense' do
      expect(offenses.size).to eq(1)
    end
  end

  context 'when file is inside app/factories and has valid suffix' do
    let(:file_path) { 'app/factories/telegram/base_factory.rb' }

    it 'does not register offenses' do
      expect(offenses).to be_empty
    end
  end

  context 'when file is outside app/factories and has invalid suffix' do
    let(:file_path) { 'app/services/base.rb' }

    it 'does not register offenses' do
      expect(offenses).to be_empty
    end
  end
end
