# 'Code is generated by Codex'
# frozen_string_literal: true

require 'rails_helper'

describe RuboCop::Cop::MoneyTracker::FactoriesFolderNaming, :config do
  include CopHelper

  subject(:offenses) { inspect_source(source, file_path) }

  let(:source) { 'class Example; end' }

  context 'when factories subdirectories do not end with _factories' do
    let(:file_path) { 'app/factories/telegram/base_factory.rb' }

    it 'does not register offenses' do
      expect(offenses).to be_empty
    end
  end

  context 'when file is inside factories subdirectory ending with _factories' do
    let(:file_path) { 'app/factories/telegram/layout_factories/base_factory.rb' }

    it 'registers an offense' do
      expect(offenses.size).to eq(1)
    end
  end

  context 'when file is inside factories subdirectory containing factory in singular form' do
    let(:file_path) { 'app/factories/telegram/layout_factory/base_factory.rb' }

    it 'registers an offense' do
      expect(offenses.size).to eq(1)
    end
  end
end
