# 'Code is generated by Codex'
# frozen_string_literal: true

require 'rails_helper'

describe RuboCop::Cop::MoneyTracker::FileNameBase, :config do
  include CopHelper

  subject(:offenses) { inspect_source(source, file_path) }

  let(:source) { 'class Example; end' }

  context 'when file is inside app/services and has invalid suffix' do
    let(:file_path) { 'app/services/telegram/base.rb' }

    it 'registers an offense' do
      expect(offenses.size).to eq(1)
    end
  end

  context 'when file is inside app/services and has valid suffix' do
    let(:file_path) { 'app/services/telegram/base_service.rb' }

    it 'does not register offenses' do
      expect(offenses).to be_empty
    end
  end

  context 'when folder is absent in naming_config.yml and file name has invalid suffix' do
    let(:file_path) { 'app/builders/telegram/base.rb' }

    it 'does not register offenses' do
      expect(offenses).to be_empty
    end
  end
end
