# 'Code is generated by Codex'
# frozen_string_literal: true

require 'rails_helper'

describe RuboCop::Cop::MoneyTracker::FolderNamingBase, :config do
  include CopHelper

  subject(:offenses) { inspect_source(source, file_path) }

  let(:source) { 'class Example; end' }

  context 'when parsers subdirectories do not end with _parsers' do
    let(:file_path) { 'app/parsers/telegram/layout_input_parser.rb' }

    it 'does not register offenses' do
      expect(offenses).to be_empty
    end
  end

  context 'when file is inside parsers subdirectory ending with _parsers' do
    let(:file_path) { 'app/parsers/telegram/add_expense_input_parsers/base_parser.rb' }

    it 'registers an offense' do
      expect(offenses.size).to eq(1)
    end
  end

  context 'when file is inside parsers subdirectory containing parser in singular form' do
    let(:file_path) { 'app/parsers/telegram/add_expense_input_parser/base_parser.rb' }

    it 'registers an offense' do
      expect(offenses.size).to eq(1)
    end
  end
end
