# 'Code is generated by Codex'
# frozen_string_literal: true

require 'rubocop'
require 'rubocop/rspec/support'
require_relative '../../../../lib/rubocop/cop/money_tracker/redundant_module_name_in_class'

RSpec.describe RuboCop::Cop::MoneyTracker::RedundantModuleNameInClass, :config do
  include CopHelper

  subject(:offenses) { inspect_source(source, file_path) }

  let(:file_path) { 'app/decorators/telegram/bot_decorator.rb' }

  context 'when class name contains one of parent module names' do
    let(:source) do
      <<~RUBY
        module Telegram
          module Bot
            class BotDecorator
            end
          end
        end
      RUBY
    end

    it 'registers an offense' do
      expect(offenses.size).to eq(1)
    end
  end

  context 'when class name does not contain any parent module name' do
    let(:source) do
      <<~RUBY
        module Telegram
          module Bot
            class Decorator
            end
          end
        end
      RUBY
    end

    it 'does not register offenses' do
      expect(offenses).to be_empty
    end
  end
end
