# 'Code is generated by Codex'
# frozen_string_literal: true

require 'rails_helper'

describe RuboCop::Cop::MoneyTracker::ServicesFolderNaming, :config do
  include CopHelper

  subject(:offenses) { inspect_source(source, file_path) }

  let(:source) { 'class Example; end' }

  context 'when services subdirectories do not end with _services' do
    let(:file_path) { 'app/services/telegram/base_service.rb' }

    it 'does not register offenses' do
      expect(offenses).to be_empty
    end
  end

  context 'when file is inside services subdirectory ending with _services' do
    let(:file_path) { 'app/services/telegram/bot_services/base_service.rb' }

    it 'registers an offense' do
      expect(offenses.size).to eq(1)
    end
  end

  context 'when file is inside services subdirectory containing service in singular form' do
    let(:file_path) { 'app/services/telegram/bot_service/base_service.rb' }

    it 'registers an offense' do
      expect(offenses.size).to eq(1)
    end
  end
end
