# Code is generated by Codex
# frozen_string_literal: true

require 'rails_helper'

describe Telegram::Messages::Layouts::Spreadsheets::Factories::AddExpenseLayoutInputParserFactory do
  describe '.run!' do
    subject(:resolved_parsers) do
      factory_names.map do |factory_name|
        described_class.run!(factory_name: factory_name, style: style)
      end
    end

    let(:style) { :const_keeper }

    context 'when action parsers are defined via multi_define' do
      let(:factory_names) { %i[list_all_actions back_to_index publish_expense] }

      it 'returns action parser for each factory' do
        expect(resolved_parsers).to all(eq(Telegram::ActionInputParser))
      end
    end

    context 'when default expense parsers are defined via multi_define' do
      let(:style) { :initializer }
      let(:factory_names) { %i[enter_date enter_range enter_money enter_category enter_comment] }

      it 'returns default parser instances with expected options' do
        parser_signatures = resolved_parsers.map { |parser| [parser.class, parser.value_alias, parser.kind] }

        expect(parser_signatures).to eq(
          [
            [Telegram::AddExpenseInputParser::Default, :date, :date_input],
            [Telegram::AddExpenseInputParser::Default, :range, :range_input],
            [Telegram::AddExpenseInputParser::Default, :money, :money_input],
            [Telegram::AddExpenseInputParser::Default, :category, :category_input],
            [Telegram::AddExpenseInputParser::Default, :comment, :comment_input]
          ]
        )
      end
    end
  end
end
