plugins:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

require:
  - ./lib/rubocop/cop/money_tracker/naming_base.rb
  - ./lib/rubocop/cop/money_tracker/file_name_base.rb
  - ./lib/rubocop/cop/money_tracker/decorators_telegram_structure.rb
  - ./lib/rubocop/cop/money_tracker/decorators_folder_naming.rb
  - ./lib/rubocop/cop/money_tracker/factories_folder_naming.rb
  - ./lib/rubocop/cop/money_tracker/parsers_folder_naming.rb
  - ./lib/rubocop/cop/money_tracker/services_folder_naming.rb
  - ./lib/rubocop/cop/money_tracker/redundant_module_name_in_class.rb

AllCops:
  NewCops: disable
  Exclude:
    - 'vendor/bundle/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'


Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LeakyLocalVariable:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

Rails/Exit:
  Exclude:
    - 'spec/rails_helper.rb'

MoneyTracker/FileNameBase:
  Enabled: true
  Include:
    - 'app/decorators/**/*.rb'
    - 'app/factories/**/*.rb'
    - 'app/parsers/**/*.rb'
    - 'app/services/**/*.rb'

MoneyTracker/DecoratorsTelegramStructure:
  Enabled: true
  Include:
    - 'app/decorators/**/*.rb'

MoneyTracker/DecoratorsFolderNaming:
  Enabled: true
  Include:
    - 'app/decorators/**/*.rb'

MoneyTracker/FactoriesFolderNaming:
  Enabled: true
  Include:
    - 'app/factories/**/*.rb'

MoneyTracker/ParsersFolderNaming:
  Enabled: true
  Include:
    - 'app/parsers/**/*.rb'

MoneyTracker/ServicesFolderNaming:
  Enabled: true
  Include:
    - 'app/services/**/*.rb'

MoneyTracker/RedundantModuleNameInClass:
  Enabled: true
  Include:
    - 'app/decorators/**/*.rb'
