plugins:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: disable
  Exclude:
    - './**'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'


Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LeakyLocalVariable:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false