# Code is generated by Codex
# frozen_string_literal: true

require 'rails_helper'

describe Telegram::Commands::Spreadsheets::ListAllService do
  subject(:result) { described_class.run!(user: user) }

  let(:user) { FactoryBot.create(:user) }

  context 'when user has spreadsheets' do
    let!(:first_spreadsheet) { FactoryBot.create(:spreadsheet, user: user, document_id: 'doc-1') }
    let!(:second_spreadsheet) { FactoryBot.create(:spreadsheet, user: user, document_id: 'doc-2') }

    before do
      FactoryBot.create(:spreadsheet, document_id: 'foreign-doc')
    end

    it 'renders only the current user spreadsheets' do
      expect(result).to eq("1) doc-1\n2) doc-2")
    end
  end

  context 'when user has no spreadsheets' do
    it 'renders an empty state message' do
      expect(result).to eq('Таблиц нет')
    end
  end
end
