# Code is generated by Codex
# frozen_string_literal: true

require 'rails_helper'

describe ::Spreadsheets::UpsertService do
  subject(:result) { described_class.run(params: params) }

  let(:params) do
    ::Spreadsheets::ParamsBuilder::Payload.new(
      document_id: 'document-id',
      sheet: ::Spreadsheets::ParamsBuilder::SheetPayload.new(
        range: 'Sheet1!A:D',
        values: [['01.01.2026', BigDecimal('250.75'), 'Food', 'Lunch']]
      )
    )
  end
  let(:sheets_service) { instance_double(Google::Apis::SheetsV4::SheetsService) }
  let(:authorizer) { instance_double(Google::Auth::ServiceAccountCredentials) }

  before do
    allow(Google::Apis::SheetsV4::SheetsService).to receive(:new).and_return(sheets_service)
    allow(Google::Auth::ServiceAccountCredentials).to receive(:make_creds).and_return(authorizer)
    allow(sheets_service).to receive(:authorization=)
    allow(authorizer).to receive(:fetch_access_token!)
  end

  context 'when google api request is successful' do
    before do
      allow(sheets_service).to receive(:append_spreadsheet_value)
    end

    it 'is valid' do
      result

      expect(result).to be_valid
      expect(sheets_service).to have_received(:append_spreadsheet_value).with(
        'document-id',
        'Sheet1!A:D',
        satisfy { |value_range| value_range.values == [['01.01.2026', BigDecimal('250.75'), 'Food', 'Lunch']] },
        value_input_option: 'USER_ENTERED'
      )
    end
  end

  context 'when google api is unavailable' do
    before do
      allow(sheets_service).to receive(:append_spreadsheet_value)
        .and_raise(Google::Apis::Error.new('Service unavailable'))
    end

    it 'is not valid' do
      expect(result).not_to be_valid
    end
  end
end
