# Code is generated by Codex
# frozen_string_literal: true

require 'rails_helper'

describe Telegram::CommonParser do
  subject(:parsed_input) { described_class.new.parse(text) }

  context 'when only action number is passed' do
    let(:text) { '2' }

    it 'returns only action number' do
      expect(parsed_input).to eq(action_number: '2')
    end
  end

  context 'when named parameters are passed' do
    let(:text) do
      '1) --date 09.03.2026 --money 12.01 --category "Продукты"'
    end

    it 'returns parsed named parameters' do
      expect(parsed_input).to eq(
        action_number: '1',
        date: '09.03.2026',
        money: '12.01',
        category: 'Продукты'
      )
    end
  end

  context 'when named parameters are passed in arbitrary order' do
    let(:text) do
      '3) --category "Транспорт" --comment "такси" --date 10.03.2026'
    end

    it 'returns parsed named parameters in hash form' do
      expect(parsed_input).to eq(
        action_number: '3',
        category: 'Транспорт',
        comment: 'такси',
        date: '10.03.2026'
      )
    end
  end
end
