# Code is generated by Codex
# frozen_string_literal: true

require 'rails_helper'

describe Telegram::DeleteSpreadsheetInputParser do
  subject(:parsed_input) { described_class.new.parse(text).transform_values(&:to_s) }

  context 'when string is valid' do
    let(:text) { '2) --document_id spreadsheet-id' }

    it 'returns parsed action_number and document_id' do
      expect(parsed_input).to eq(action_number: '2', document_id: 'spreadsheet-id')
    end
  end

  context 'when document_id is wrapped in double quotes' do
    let(:text) { '2) --document_id "spreadsheet id"' }

    it 'returns parsed action_number and quoted document_id' do
      expect(parsed_input).to eq(action_number: '2', document_id: 'spreadsheet id')
    end
  end

  context 'when string is invalid' do
    let(:text) { '2) --document_id' }

    it 'raises parse error' do
      expect { described_class.new.parse(text) }.to raise_error(Parslet::ParseFailed)
    end
  end
end
