# Code is generated by Codex
# frozen_string_literal: true

require 'rails_helper'

describe Telegram::AddExpenseInput::WithNamedInputsParser do
  subject(:parsed_input) do
    described_class
      .new(:with_named_inputs, :date_input, :money_input, :category_input, :comment_input, **parser_named_parameters)
      .parse(text)
  end

  let(:parser_named_parameters) { {} }

  context 'when all named parameters are passed' do
    let(:text) do
      '1) --date 01.02.2026 --money 12.01 --category "Продукты" --comment "за хлеб"'
    end

    it 'returns parsed values with comment' do
      expect(parsed_input.transform_values(&:to_s)).to eq(
        action_number: '1',
        date: '01.02.2026',
        money: '12.01',
        category: 'Продукты',
        comment: 'за хлеб'
      )
    end
  end

  context 'when optional comment parameter is not passed' do
    let(:text) do
      '1) --date 01.02.2026 --money 12.01 --category "Продукты"'
    end

    it 'returns parsed values without comment' do
      expect(parsed_input.transform_values(&:to_s)).to eq(
        action_number: '1',
        date: '01.02.2026',
        money: '12.01',
        category: 'Продукты'
      )
    end
  end

  context 'when all parameters are passed without whitespaces' do
    let(:text) do
      '1)--date01.02.2026--money12.01--category"Продукты"--comment"за хлеб"'
    end

    it 'returns parsed values with comment' do
      expect(parsed_input.transform_values(&:to_s)).to eq(
        action_number: '1',
        date: '01.02.2026',
        money: '12.01',
        category: 'Продукты',
        comment: 'за хлеб'
      )
    end
  end

  context 'when parameters are passed without whitespaces and without comment' do
    let(:text) do
      '1)--date01.02.2026--money12.01--category"Продукты"'
    end

    it 'returns parsed values without comment' do
      expect(parsed_input.transform_values(&:to_s)).to eq(
        action_number: '1',
        date: '01.02.2026',
        money: '12.01',
        category: 'Продукты'
      )
    end
  end

  context 'when custom named parameters are passed to parser' do
    let(:parser_named_parameters) do
      { date: '--d', money: '--m', category: '--c', comment: '--note' }
    end
    let(:text) do
      '1) --d 01.02.2026 --m 12.01 --c "Продукты" --note "за хлеб"'
    end

    it 'returns parsed values for custom aliases' do
      expect(parsed_input.transform_values(&:to_s)).to eq(
        action_number: '1',
        date: '01.02.2026',
        money: '12.01',
        category: 'Продукты',
        comment: 'за хлеб'
      )
    end
  end
end
