# Code is generated by Codex
# frozen_string_literal: true

require 'rails_helper'

class TestBotDecorator < Telegram::BotDecorators::BotDecorator
  def message_text
    __getobj__[:message_text]
  end

  def send_message(text); end

  delegate :username, to: :message
end

TestMessage = Struct.new(:username, keyword_init: true)

describe Telegram::MessageHandler do
  subject(:run_steps) do
    steps.each do |step|
      described_class.run(bot: step[:bot])
    end
    user.reload
  end

  let(:user) { FactoryBot.create(:user) }
  let(:steps) { [] }

  context 'when user start dialog' do
    let(:step1_start_dialog) do
      {
        bot: TestBotDecorator.new(
          { message_text: '/start' },
          TestMessage.new(username: user.telegram_username)
        )
      }
    end
    let(:steps) { [step1_start_dialog] }

    it do
      run_steps
      expect(user.layout_cursor_action.layout).to eq(Index.name)
    end

    context 'when user call add_table' do
      let(:step2_choose_add_table) do
        action_number = Index.action_number_for(:add_table)
        {
          bot: TestBotDecorator.new(
            { message_text: action_number.to_s },
            TestMessage.new(username: user.telegram_username)
          )
        }
      end

      let(:steps) { [step1_start_dialog, step2_choose_add_table] }

      it do
        run_steps
        expect(user.layout_cursor_action.layout).to eq(New.name)
      end

      context 'when user call enter_document_id' do
        let(:document_id) { 'MoneyTrackerSpreadsheet' }
        let(:spreadsheet) { Spreadsheet.find_by(user_id: user.id, document_id: document_id) }

        let(:step3_choose_enter_document_id) do
          action_number = New.action_number_for(:enter_document_id)
          {
            bot: TestBotDecorator.new(
              { message_text: "#{action_number}) #{document_id}" },
              TestMessage.new(username: user.telegram_username)
            )
          }
        end

        let(:steps) do
          [
            step1_start_dialog,
            step2_choose_add_table,
            step3_choose_enter_document_id
          ]
        end

        it do
          run_steps
          expect(user.layout_cursor_action.layout).to eq(ListTables.name)
          expect(spreadsheet).to be_valid
        end
      end
    end
  end
end
