# Code is generated by Codex
# frozen_string_literal: true

require 'rails_helper'

class TestBotDecorator < Telegram::Bot::BotDecorator
  def message_text
    __getobj__[:message_text]
  end

  def send_message(text); end

  delegate :username, to: :message
end

TestMessage = Struct.new(:username, keyword_init: true)

describe Telegram::MessageHandler do
  subject(:run_steps) do
    steps.each do |step|
      described_class.run(bot: step[:bot])
    end
    user.reload
  end

  let(:user) { FactoryBot.create(:user) }
  let(:steps) { [] }

  context 'when user start dialog' do
    let(:step1_start_dialog) do
      {
        bot: TestBotDecorator.new(
          { message_text: '/start' },
          TestMessage.new(username: user.telegram_username)
        )
      }
    end

    let(:steps) { [step1_start_dialog] }

    it do
      run_steps
      expect(user.layout_cursor_action.layout).to eq(Index.name)
    end

    context 'when user call add_table' do
      let(:step2_choose_add_table) do
        action_number = Index.action_number_for(:add_table)
        {
          bot: TestBotDecorator.new(
            { message_text: action_number.to_s },
            TestMessage.new(username: user.telegram_username)
          )
        }
      end

      let(:steps) { [step1_start_dialog, step2_choose_add_table] }

      it do
        run_steps
        expect(user.layout_cursor_action.layout).to eq(New.name)
      end

      context 'when user call enter_spreadsheets_params' do
        let(:document_id) { 'MoneyTrackerSpreadsheet' }
        let(:expense_range) { 'Sheet1!A1:B1' }
        let(:spreadsheet) { Spreadsheet.find_by(user_id: user.id, document_id: document_id) }

        let(:step3_choose_enter_document_id) do
          action_number = New.action_number_for(:enter_spreadsheets_params)
          {
            bot: TestBotDecorator.new(
              { message_text: "#{action_number}) --document_id #{document_id} --expense_range \"#{expense_range}\"" },
              TestMessage.new(username: user.telegram_username)
            )
          }
        end

        let(:steps) { [step1_start_dialog, step2_choose_add_table, step3_choose_enter_document_id] }

        it do
          run_steps
          expect(user.layout_cursor_action.layout).to eq(ListTables.name)
          expect(spreadsheet).to be_valid
          expect(spreadsheet.expense_range).to eq(expense_range)
        end

        context 'when user call list_tables' do
          let(:step4_choose_list_tables) do
            action_number = ListTables.action_number_for(:list_tables)
            {
              bot: TestBotDecorator.new(
                { message_text: action_number.to_s },
                TestMessage.new(username: user.telegram_username)
              )
            }
          end

          let(:steps) do
            [step1_start_dialog, step2_choose_add_table, step3_choose_enter_document_id, step4_choose_list_tables]
          end

          it do
            run_steps
            expect(user.layout_cursor_action.layout).to eq(ListTables.name)
          end
        end

        context 'when user call delete_table with named document_id' do
          let(:document_id) { 'Money-Tracker-Spreadsheet' }
          let(:step4_choose_delete_table) do
            action_number = ListTables.action_number_for(:delete_table)
            {
              bot: TestBotDecorator.new(
                { message_text: "#{action_number}) --document_id \"#{document_id}\"" },
                TestMessage.new(username: user.telegram_username)
              )
            }
          end

          let(:steps) do
            [step1_start_dialog, step2_choose_add_table, step3_choose_enter_document_id, step4_choose_delete_table]
          end

          it do
            run_steps
            expect(user.layout_cursor_action.layout).to eq(Index.name)
            expect(Spreadsheet.find_by(user_id: user.id, document_id: document_id)).to be_nil
          end
        end

        context 'when user call data_actions' do
          let(:step4_choose_data_actions) do
            action_number = ListTables.action_number_for(:data_actions)
            {
              bot: TestBotDecorator.new(
                { message_text: "#{action_number}) #{document_id}" },
                TestMessage.new(username: user.telegram_username)
              )
            }
          end

          let(:chat_context) { ChatContext.find_by(user_id: user.id) }

          let(:steps) do
            [step1_start_dialog, step2_choose_add_table, step3_choose_enter_document_id, step4_choose_data_actions]
          end

          it do
            run_steps
            expect(user.layout_cursor_action.layout).to eq(DataActionsLayout.name)
            expect(chat_context.spreadsheet_id).to eq(spreadsheet.id)
          end

          context 'when user call add_expense' do
            let(:step5_choose_add_expense) do
              action_number = DataActionsLayout.action_number_for(:add_expense)
              {
                bot: TestBotDecorator.new(
                  { message_text: action_number.to_s },
                  TestMessage.new(username: user.telegram_username)
                )
              }
            end

            let(:steps) do
              [step1_start_dialog, step2_choose_add_table, step3_choose_enter_document_id, step4_choose_data_actions,
               step5_choose_add_expense]
            end

            it do
              run_steps
              expect(user.layout_cursor_action.layout).to eq(AddExpenseLayout.name)
            end

            context 'when user call enter_date' do
              let(:step6_choose_enter_date) do
                action_number = AddExpenseLayout.action_number_for(:enter_date)
                {
                  bot: TestBotDecorator.new(
                    { message_text: "#{action_number}) 01.01.2025" },
                    TestMessage.new(username: user.telegram_username)
                  )
                }
              end

              let(:spreadsheet_form) { SpreadsheetForm.find_by(user_id: user.id, spreadsheet_id: spreadsheet.id) }
              let(:date_form_input) { DateFormInput.find_by(form_id: spreadsheet_form.id) }

              let(:steps) do
                [step1_start_dialog, step2_choose_add_table, step3_choose_enter_document_id, step4_choose_data_actions,
                 step5_choose_add_expense, step6_choose_enter_date]
              end

              it do
                run_steps
                expect(user.layout_cursor_action.layout).to eq(AddExpenseLayout.name)
                expect(date_form_input.date).to eq('01.01.2025')
              end
            end

            context 'when user call enter_range' do
              let(:step6_choose_enter_range) do
                action_number = AddExpenseLayout.action_number_for(:enter_range)
                {
                  bot: TestBotDecorator.new(
                    { message_text: "#{action_number}) Sheet1!A:D" },
                    TestMessage.new(username: user.telegram_username)
                  )
                }
              end

              let(:spreadsheet_form) { SpreadsheetForm.find_by(user_id: user.id, spreadsheet_id: spreadsheet.id) }
              let(:range_form_input) { RangeFormInput.find_by(form_id: spreadsheet_form.id) }

              let(:steps) do
                [step1_start_dialog, step2_choose_add_table, step3_choose_enter_document_id, step4_choose_data_actions,
                 step5_choose_add_expense, step6_choose_enter_range]
              end

              it do
                run_steps
                expect(user.layout_cursor_action.layout).to eq(AddExpenseLayout.name)
                expect(range_form_input.range).to eq('Sheet1!A:D')
              end
            end

            context 'when user call enter_money' do
              let(:step6_choose_enter_money) do
                action_number = AddExpenseLayout.action_number_for(:enter_money)
                {
                  bot: TestBotDecorator.new(
                    { message_text: "#{action_number}) 2.75" },
                    TestMessage.new(username: user.telegram_username)
                  )
                }
              end

              let(:spreadsheet_form) { SpreadsheetForm.find_by(user_id: user.id, spreadsheet_id: spreadsheet.id) }
              let(:money_form_input) { MoneyFormInput.find_by(form_id: spreadsheet_form.id) }

              let(:steps) do
                [step1_start_dialog, step2_choose_add_table, step3_choose_enter_document_id, step4_choose_data_actions,
                 step5_choose_add_expense, step6_choose_enter_money]
              end

              it do
                run_steps
                expect(user.layout_cursor_action.layout).to eq(AddExpenseLayout.name)
                expect(money_form_input.money).to eq(2.75)
              end
            end

            context 'when user call enter_category' do
              let(:step6_choose_enter_category) do
                action_number = AddExpenseLayout.action_number_for(:enter_category)
                {
                  bot: TestBotDecorator.new(
                    { message_text: "#{action_number}) 'Домашний интернет'" },
                    TestMessage.new(username: user.telegram_username)
                  )
                }
              end

              let(:spreadsheet_form) { SpreadsheetForm.find_by(user_id: user.id, spreadsheet_id: spreadsheet.id) }
              let(:category_form_input) { CategoryFormInput.find_by(form_id: spreadsheet_form.id) }

              let(:steps) do
                [step1_start_dialog, step2_choose_add_table, step3_choose_enter_document_id, step4_choose_data_actions,
                 step5_choose_add_expense, step6_choose_enter_category]
              end

              it do
                run_steps
                expect(user.layout_cursor_action.layout).to eq(AddExpenseLayout.name)
                expect(category_form_input.category).to eq('Домашний интернет')
              end
            end

            context 'when user call enter_comment' do
              let(:step6_choose_enter_comment) do
                action_number = AddExpenseLayout.action_number_for(:enter_comment)
                {
                  bot: TestBotDecorator.new(
                    { message_text: "#{action_number}) 'Купил тапки'" },
                    TestMessage.new(username: user.telegram_username)
                  )
                }
              end

              let(:spreadsheet_form) { SpreadsheetForm.find_by(user_id: user.id, spreadsheet_id: spreadsheet.id) }
              let(:comment_form_input) { CommentFormInput.find_by(form_id: spreadsheet_form.id) }

              let(:steps) do
                [step1_start_dialog, step2_choose_add_table, step3_choose_enter_document_id, step4_choose_data_actions,
                 step5_choose_add_expense, step6_choose_enter_comment]
              end

              it do
                run_steps
                expect(user.layout_cursor_action.layout).to eq(AddExpenseLayout.name)
                expect(comment_form_input.comment).to eq('Купил тапки')
              end
            end

            context 'when user call enter_all_params' do
              let(:step6_choose_enter_date) do
                action_number = AddExpenseLayout.action_number_for(:enter_date)
                {
                  bot: TestBotDecorator.new(
                    { message_text: "#{action_number}) 01.01.2025" },
                    TestMessage.new(username: user.telegram_username)
                  )
                }
              end

              let(:step7_choose_enter_money) do
                action_number = AddExpenseLayout.action_number_for(:enter_money)
                {
                  bot: TestBotDecorator.new(
                    { message_text: "#{action_number}) 2.75" },
                    TestMessage.new(username: user.telegram_username)
                  )
                }
              end

              let(:step8_choose_enter_category) do
                action_number = AddExpenseLayout.action_number_for(:enter_category)
                {
                  bot: TestBotDecorator.new(
                    { message_text: "#{action_number}) 'Домашний интернет'" },
                    TestMessage.new(username: user.telegram_username)
                  )
                }
              end

              let(:step9_choose_enter_comment) do
                action_number = AddExpenseLayout.action_number_for(:enter_comment)
                {
                  bot: TestBotDecorator.new(
                    { message_text: "#{action_number}) 'Купил тапки'" },
                    TestMessage.new(username: user.telegram_username)
                  )
                }
              end

              let(:spreadsheet_form) { SpreadsheetForm.find_by(user_id: user.id, spreadsheet_id: spreadsheet.id) }
              let(:date_form_input) { DateFormInput.find_by(form_id: spreadsheet_form.id) }
              let(:money_form_input) { MoneyFormInput.find_by(form_id: spreadsheet_form.id) }
              let(:category_form_input) { CategoryFormInput.find_by(form_id: spreadsheet_form.id) }
              let(:comment_form_input) { CommentFormInput.find_by(form_id: spreadsheet_form.id) }

              let(:steps) do
                [step1_start_dialog, step2_choose_add_table, step3_choose_enter_document_id, step4_choose_data_actions,
                 step5_choose_add_expense, step6_choose_enter_date, step7_choose_enter_money,
                 step8_choose_enter_category, step9_choose_enter_comment]
              end

              it do
                run_steps
                expect(user.layout_cursor_action.layout).to eq(AddExpenseLayout.name)
                expect(date_form_input.date).to eq('01.01.2025')
                expect(money_form_input.money).to eq(2.75)
                expect(category_form_input.category).to eq('Домашний интернет')
                expect(comment_form_input.comment).to eq('Купил тапки')
              end
            end
          end
        end
      end
    end
  end
end
