# Code is generated by Codex
# frozen_string_literal: true

require 'rails_helper'

class TestBotDecorator < Telegram::BotDecorators::BotDecorator
  def message_text
    __getobj__[:message_text]
  end

  def send_message(text); end

  delegate :username, to: :message
end

TestMessage = Struct.new(:username, keyword_init: true)

steps = []

describe Telegram::MessageHandler do
  subject(:run_steps) do
    steps.each do |step|
      described_class.run(bot: step[:bot])
    end
    user.reload
  end

  let(:user) { FactoryBot.create(:user) }

  context 'when user start dialog' do
    let(:step1_start_dialog) do
      {
        bot: TestBotDecorator.new(
          { message_text: '/start' },
          TestMessage.new(username: user.telegram_username)
        )
      }
    end

    before { steps << step1_start_dialog }

    it do
      run_steps
      expect(user.layout_cursor_action.layout).to eq(Index.name)
    end

    context 'when user call add_table' do
      let(:step2_choose_add_table) do
        action_number = Index.action_number_for(:add_table)
        {
          bot: TestBotDecorator.new(
            { message_text: action_number.to_s },
            TestMessage.new(username: user.telegram_username)
          )
        }
      end

      before { steps << step2_choose_add_table }

      it do
        run_steps
        expect(user.layout_cursor_action.layout).to eq(New.name)
      end

      context 'when user call enter_document_id' do
        let(:document_id) { 'MoneyTrackerSpreadsheet' }
        let(:spreadsheet) { Spreadsheet.find_by(user_id: user.id, document_id: document_id) }

        let(:step3_choose_enter_document_id) do
          action_number = New.action_number_for(:enter_document_id)
          {
            bot: TestBotDecorator.new(
              { message_text: "#{action_number}) #{document_id}" },
              TestMessage.new(username: user.telegram_username)
            )
          }
        end

        before { steps << step3_choose_enter_document_id }

        it do
          run_steps
          expect(user.layout_cursor_action.layout).to eq(ListTables.name)
          expect(spreadsheet).to be_valid
        end

        context 'when user call list_tables' do
          let(:step4_choose_list_tables) do
            action_number = ListTables.action_number_for(:list_tables)
            {
              bot: TestBotDecorator.new(
                { message_text: action_number.to_s },
                TestMessage.new(username: user.telegram_username)
              )
            }
          end

          before { steps << step4_choose_list_tables }

          it do
            run_steps
            expect(user.layout_cursor_action.layout).to eq(ListTables.name)
          end
        end

        context 'when user call data_actions' do
          let(:step4_choose_data_actions) do
            action_number = ListTables.action_number_for(:data_actions)
            {
              bot: TestBotDecorator.new(
                { message_text: action_number.to_s },
                TestMessage.new(username: user.telegram_username)
              )
            }
          end

          it do
            run_steps
            expect(user.layout_cursor_action.layout).to eq(ListTables.name)
          end
        end
      end
    end
  end
end
