name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run rubocop and specs in Docker Compose
        run: docker compose up --build --abort-on-container-exit --exit-code-from spec spec

      - name: Stop containers
        if: always()
        run: docker compose down -v --remove-orphans
